version: "3.8"

services:

  shop_spring_api:
    depends_on:
      - shop_mysql_db
    image: chhaichivon/spring-demo-api:v1.0.10
    container_name: shop_spring_api
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://shop_mysql_db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    networks:
      - shop-network
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  shop_mysql_db:
    image: mysql:5.7
    container_name: shop_mysql_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - shop-network
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  shop-network:
    name: shop-network